# Generated by Django 4.1 on 2022-08-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=15, verbose_name='사용자ID')),
                ('nickname', models.CharField(max_length=10, verbose_name='닉네임')),
                ('password', models.CharField(max_length=15, verbose_name='사용자비밀번호')),
            ],
        ),
    ]
