# Generated by Django 4.1 on 2022-08-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, default="['gray', 'blue', 'green', 'yellow', 'orange', 'red', 'purple']", max_length=100, null=True),
        ),
    ]
